apiVersion: apps/v1
kind: Deployment
metadata:
  name: sinatra-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sinatra-app
  template:
    metadata:
      labels:
        app: sinatra-app
    spec:
      containers:
      - name: sinatra-app-container
        image: sinatra-app:1.2.2
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: sinatra-app-config
        volumeMounts:
        - name: sinatra-app-volume
          mountPath: /data
      volumes:
        - name: sinatra-app-volume
          persistentVolumeClaim:
            claimName: sinatra-app-pvc