apiVersion: v1
kind: PersistentVolume
metadata:
  name: sinatra-app-pv
  labels:
    type: local
    app: sinatra-app
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/data
    type: Directory